spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  secret:
    jwt: ${JWT_SECRET}
  allowed-origin:
    url: ${ALLOWED_ORIGIN_URL}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: Message
